CheezeMVC/Models/Cheeze.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace CheezeMVC.Models
{
    public class Cheeze
    {
        public string Name { get; set; }
        public string Description { get; set; }
        public List<Cheeze> cheezelist = new List<Cheeze>();
    }
}

CheezeMVC/Models/ErrorViewModel.cs
using System;

namespace CheezeMVC.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

CheezeMVC/Controllers/CheezeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using CheezeMVC.Models;
using Microsoft.AspNetCore.Mvc;

namespace CheezeMVC.Controllers
{
    public class CheezeController : Controller
    {

       // static private Dictionary<string, string> Cheeses = new Dictionary<string, string>();
       static public List<Cheeze> Cheezes = new List<Cheeze>();
       

       //public Cheeze cheeze { get; set; }
        public Cheeze cheeze = new Cheeze();
        public IActionResult Index()
        {
            ViewBag.cheezes = Cheezes;
            return View();
        }

        public IActionResult Add()
        {
            return View();
        }

        public IActionResult Remove()
        {
            ViewBag.cheezes = Cheezes;
            return View();
        }
        public IActionResult Remove2()
        {
            ViewBag.cheezes = Cheezes;
            return View();
        }

        [HttpPost]
        [Route("/Cheeze/Remove")]
        public IActionResult LessCheese(Cheeze cheeze)
        {
            //Take away the old cheeses from the list
            foreach (Cheeze item in cheeze.cheezelist)
            {
                Cheezes.Remove(item);
                
            }
            return Redirect("/Cheeze");

        }

        [HttpPost]
        [Route("/Cheeze/Add")]
        public IActionResult NewCheese(Cheeze cheeze)
        {

            //Add the new cheese to my existing cheeses
            Cheezes.Add(cheeze);

            return Redirect("/Cheeze");

        }
        [HttpPost]
        [Route("/Cheeze/Remove2")]
        public IActionResult RemoveOne(Cheeze cheeze)
        {
            //Take away one cheese from the list
            Cheezes.Remove(cheeze);
            return Redirect("/Cheeze");

        }


    }
}

CheezeMVC/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using CheezeMVC.Models;

namespace CheeseMVC.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

CheezeMVC/Views/Cheeze/Add.cshtml
@model CheezeMVC.Models.Cheeze

@{
    ViewData["Title"] = "Add";

}

<h1>Add Cheese</h1>

<form method="post">
    <p>Enter name of the cheese here:</p>

    <input name="Name" type="text" />
    <p>Enter description here</p>

    <input name="Description" type="text" />
    <input type="submit" value="Add Cheese" />
</form>

CheezeMVC/Views/Cheeze/Index.cshtml
@model CheezeMVC.Models.Cheeze
@{


}

<h1>My Cheese</h1>

<p><a asp-controller="Cheeze" asp-action="Add">Add Cheese</a> </p>

@if (ViewBag.cheezes.Count == 0)
{
    <p>No Cheeses Yet</p>
}
<ul>
    @foreach (Cheeze cheeze in ViewBag.cheezes)
    {
        <li>@cheeze.Name :   @cheeze.Description</li>
    }


</ul>

@if (ViewBag.cheezes.Count != 0)
{
    <p><a asp-controller="Cheeze" asp-action="Remove">Remove Cheese</a> </p>
}

@if (ViewBag.cheezes.Count != 0)
{
    <p><a asp-controller="Cheeze" asp-action="Remove2">Remove Just one Cheese</a> </p>
}

CheezeMVC/Views/Cheeze/Remove.cshtml
@model CheezeMVC.Models.Cheeze

@{
    ViewData["Title"] = "Remove";
}


<h1>Remove Cheese</h1>

<form method="post" action="/cheeze/Remove">
    @foreach (Cheeze cheeze in ViewBag.cheezes)
    {


        <input type="checkbox" name="cheezelist" value="cheeze">@cheeze.Name<br />

    }

    <input type="submit" value="Remove" />
</form>

CheezeMVC/Views/Cheeze/Remove2.cshtml
@model CheezeMVC.Models.Cheeze
@{
    ViewData["Title"] = "Remove2";
}

<h1>Remove Just One</h1>

<form method="post">
    <select name="cheeze">
        @foreach (Cheeze cheeze in ViewBag.cheezes)
        {
            <option value='cheeze'>@cheeze.Name</option>
            

        }


    </select>
    <input type="submit" value="Take it Away" />
</form>

CheezeMVC/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

CheezeMVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - CheezeMVC</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">CheezeMVC</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Cheeze" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Cheeze" asp-action="Add">Add</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - CheezeMVC - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>